
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMA FOR IDENTIFIER IN LPAREN NUMBER RANGE RPARENfor_loop : FOR IDENTIFIER IN range_expr COLONrange_expr : RANGE LPAREN NUMBER RPAREN\n                  | RANGE LPAREN NUMBER COMMA NUMBER RPAREN\n                  | RANGE LPAREN NUMBER COMMA NUMBER COMMA NUMBER RPAREN'
    
_lr_action_items = {'FOR':([0,],[2,]),'$end':([1,7,],[0,-1,]),'IDENTIFIER':([2,],[3,]),'IN':([3,],[4,]),'RANGE':([4,],[6,]),'COLON':([5,10,14,16,],[7,-2,-3,-4,]),'LPAREN':([6,],[8,]),'NUMBER':([8,11,13,],[9,12,15,]),'RPAREN':([9,12,15,],[10,14,16,]),'COMMA':([9,12,],[11,13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'for_loop':([0,],[1,]),'range_expr':([4,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> for_loop","S'",1,None,None,None),
  ('for_loop -> FOR IDENTIFIER IN range_expr COLON','for_loop',5,'p_for_loop','for.py',40),
  ('range_expr -> RANGE LPAREN NUMBER RPAREN','range_expr',4,'p_range_expr','for.py',44),
  ('range_expr -> RANGE LPAREN NUMBER COMMA NUMBER RPAREN','range_expr',6,'p_range_expr','for.py',45),
  ('range_expr -> RANGE LPAREN NUMBER COMMA NUMBER COMMA NUMBER RPAREN','range_expr',8,'p_range_expr','for.py',46),
]
